name: Build and Release Resume

on:
  push:
    paths:
      - 'public/data/resume.tex'
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: public/data/resume.tex

      - name: Create/Update Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Resume"
          files: |
            resume.pdf
